//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSCDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        

        public long SNO_ { get; set; }
        public Nullable<long> Username { get; set; }
        public long ProductId { get; set; }
        public string productname { get; set; }
        public short quantity { get; set; }
        public double price { get; set; }
    }
}
