//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSCDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public long SNO_ { get; set; }
        public long productId { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public double price { get; set; }
        public double discount { get; set; }
        public short quantity { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public Nullable<System.DateTime> startsAt { get; set; }
        public Nullable<System.DateTime> endsAt { get; set; }
    }
}
