//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSCDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public long id { get; set; }
        public string Name { get; set; }
        public string mobile { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime registeredAt { get; set; }
        public Nullable<System.DateTime> lastLogin { get; set; }
    }
}
